### ISSUE TITLE
problem compiling the plugin

### ISSUE THREAD

**Issue by ghost** [chadmv/cvwrap#1]
Hi Chad 

Thank you for sharing. iam having trouble compiling the plugin. 
this is my output, can you tell me what iam doing wrong. 

---

C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build>cmake -G "Visual St
udio 11 2012 Win64" -DMAYA_VERSION=2016 ../
-- The C compiler identification is MSVC 17.0.60610.1
-- The CXX compiler identification is MSVC 17.0.60610.1
-- Check for working C compiler using: Visual Studio 11 2012 Win64
-- Check for working C compiler using: Visual Studio 11 2012 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 11 2012 Win64
-- Check for working CXX compiler using: Visual Studio 11 2012 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Maya: C:/Program Files/Autodesk/Maya2016/include
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/PMnicolai/Desktop/cvwrap-master/cv
wrap-master/build

C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build>cmake --build .  --
config Release
Microsoft (R) Build Engine version 4.6.81.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 29-09-2015 14:39:41.
Project "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\ALL_BUILD
.vcxproj" on node 1 (default targets).
Project "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\ALL_BUILD
.vcxproj" (1) is building "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-mast
er\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Release\ZERO_CHECK\".
InitializeBuildStatus:
  Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild" because "Alway
  sCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because C:/Users/PMnicolai/Desktop/cvwrap-maste
  r/cvwrap-master/build/CMakeFiles/generate.stamp is up-to-date.
  CMake does not need to re-run because C:/Users/PMnicolai/Desktop/cvwrap-maste
  r/cvwrap-master/build/src/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild".
  Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\b
uild\ZERO_CHECK.vcxproj" (default targets).

Project "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\ALL_BUILD
.vcxproj" (1) is building "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-mast
er\build\src\cvwrap.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "cvwrap.dir\Release\".
  Creating directory "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\bu
  ild\src\Release\".
InitializeBuildStatus:
  Creating "cvwrap.dir\Release\cvwrap.unsuccessfulbuild" because "AlwaysCreate"
   was specified.
CustomBuild:
  Building Custom Rule C:/Users/PMnicolai/Desktop/cvwrap-master/cvwrap-master/s
  rc/CMakeLists.txt
  CMake does not need to re-run because C:\Users\PMnicolai\Desktop\cvwrap-maste
  r\cvwrap-master\build\src\CMakeFiles\generate.stamp is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\x86_amd64\CL.exe /
  c /I"C:\Program Files\Autodesk\Maya2016\include" /nologo /W3 /WX- /O2 /Ob2 /D
   WIN32 /D _WINDOWS /D NDEBUG /D REQUIRE_IOSTREAM /D _BOOL /D NT_PLUGIN /D "CM
  AKE_INTDIR=\"Release\"" /D cvwrap_EXPORTS /D _WINDLL /D _MBCS /Gm- /EHsc /MD
  /GS /arch:AVX /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"cvwrap.dir\Release
  \" /Fd"cvwrap.dir\Release\vc110.pdb" /Gd /TP /errorReport:queue "C:\Users\PM
  nicolai\Desktop\cvwrap-master\cvwrap-master\src\pluginMain.cpp" "C:\Users\PMn
  icolai\Desktop\cvwrap-master\cvwrap-master\src\cvWrapCmd.cpp" "C:\Users\PMnic
  olai\Desktop\cvwrap-master\cvwrap-master\src\cvWrapDeformer.cpp" "C:\Users\PM
  nicolai\Desktop\cvwrap-master\cvwrap-master\src\bindingio.cpp" "C:\Users\PMni
  colai\Desktop\cvwrap-master\cvwrap-master\src\common.cpp"
  pluginMain.cpp
  cvWrapCmd.cpp
  cvWrapDeformer.cpp
  bindingio.cpp
  common.cpp
  Generating Code...
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\x86_amd64\link.exe
   /ERRORREPORT:QUEUE /OUT:"C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-mas
  ter\build\src\Release\cvwrap.mll" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:/Progra
  m Files/Autodesk/Maya2016/lib" /LIBPATH:"C:/Program Files/Autodesk/Maya2016/l
  ib/Release" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.
  lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\Program Files\Autodes
  k\Maya2016\lib\OpenMaya.lib" "C:\Program Files\Autodesk\Maya2016\lib\OpenMaya
  Anim.lib" "C:\Program Files\Autodesk\Maya2016\lib\OpenMayaFX.lib" "C:\Program
   Files\Autodesk\Maya2016\lib\OpenMayaRender.lib" "C:\Program Files\Autodesk\M
  aya2016\lib\OpenMayaUI.lib" "C:\Program Files\Autodesk\Maya2016\lib\Foundatio
  n.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:
  embed /PDB:"C:/Users/PMnicolai/Desktop/cvwrap-master/cvwrap-master/build/src/
  Release/cvwrap.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLI
  B:"C:/Users/PMnicolai/Desktop/cvwrap-master/cvwrap-master/build/src/Release/c
  vwrap.lib" /MACHINE:X64  /machine:x64 /export:initializePlugin /export:uninit
  ializePlugin /DLL cvwrap.dir\Release\pluginMain.obj
  cvwrap.dir\Release\cvWrapCmd.obj
  cvwrap.dir\Release\cvWrapDeformer.obj
  cvwrap.dir\Release\bindingio.obj
  cvwrap.dir\Release\common.obj
     Creating library C:/Users/PMnicolai/Desktop/cvwrap-master/cvwrap-master/bu
  ild/src/Release/cvwrap.lib and object C:/Users/PMnicolai/Desktop/cvwrap-maste
  r/cvwrap-master/build/src/Release/cvwrap.exp
cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewCrea
teBuffer referenced in function "int __cdecl EnqueueBuffer(class MAutoCLMem &,u
nsigned __int64,void *)" (?EnqueueBuffer@@YAHAEAVMAutoCLMem@@_KPEAX@Z) [C:\User
s\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\src\cvwrap.vcxproj]
cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewSetK
ernelArg referenced in function "public: virtual enum MPxGPUDeformer::DeformerS
tatus __cdecl CVWrapGPU::evaluate(class MDataBlock &,class MEvaluationNode cons
t &,class MPlug const &,unsigned int,class MAutoCLMem,class MAutoCLEvent,class
MAutoCLMem,class MAutoCLEvent &)" (?evaluate@CVWrapGPU@@UEAA?AW4DeformerStatus@
MPxGPUDeformer@@AEAVMDataBlock@@AEBVMEvaluationNode@@AEBVMPlug@@IVMAutoCLMem@@V
MAutoCLEvent@@V7@AEAV8@@Z) [C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-mas
ter\build\src\cvwrap.vcxproj]
cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewGetK
ernelWorkGroupInfo referenced in function "public: virtual enum MPxGPUDeformer:
:DeformerStatus __cdecl CVWrapGPU::evaluate(class MDataBlock &,class MEvaluatio
nNode const &,class MPlug const &,unsigned int,class MAutoCLMem,class MAutoCLEv
ent,class MAutoCLMem,class MAutoCLEvent &)" (?evaluate@CVWrapGPU@@UEAA?AW4Defor
merStatus@MPxGPUDeformer@@AEAVMDataBlock@@AEBVMEvaluationNode@@AEBVMPlug@@IVMAu
toCLMem@@VMAutoCLEvent@@V7@AEAV8@@Z) [C:\Users\PMnicolai\Desktop\cvwrap-master\
cvwrap-master\build\src\cvwrap.vcxproj]
cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewEnqu
eueWriteBuffer referenced in function "int __cdecl EnqueueBuffer(class MAutoCLM
em &,unsigned __int64,void *)" (?EnqueueBuffer@@YAHAEAVMAutoCLMem@@_KPEAX@Z) [C
:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\src\cvwrap.vcxproj]
cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewEnqu
eueNDRangeKernel referenced in function "public: virtual enum MPxGPUDeformer::D
eformerStatus __cdecl CVWrapGPU::evaluate(class MDataBlock &,class MEvaluationN
ode const &,class MPlug const &,unsigned int,class MAutoCLMem,class MAutoCLEven
t,class MAutoCLMem,class MAutoCLEvent &)" (?evaluate@CVWrapGPU@@UEAA?AW4Deforme
rStatus@MPxGPUDeformer@@AEAVMDataBlock@@AEBVMEvaluationNode@@AEBVMPlug@@IVMAuto
CLMem@@VMAutoCLEvent@@V7@AEAV8@@Z) [C:\Users\PMnicolai\Desktop\cvwrap-master\cv
wrap-master\build\src\cvwrap.vcxproj]
C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\src\Release\cvwrap
.mll : fatal error LNK1120: 5 unresolved externals [C:\Users\PMnicolai\Desktop\
cvwrap-master\cvwrap-master\build\src\cvwrap.vcxproj]
Done Building Project "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\b
uild\src\cvwrap.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\b
uild\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\ALL_BUILD.vcxproj
" (default target) (1) ->
"C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\src\cvwrap.vcxpro
j" (default target) (3) ->
(Link target) ->
  cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewCr
eateBuffer referenced in function "int __cdecl EnqueueBuffer(class MAutoCLMem &
,unsigned __int64,void *)" (?EnqueueBuffer@@YAHAEAVMAutoCLMem@@_KPEAX@Z) [C:\Us
ers\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\src\cvwrap.vcxproj]
  cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewSe
tKernelArg referenced in function "public: virtual enum MPxGPUDeformer::Deforme
rStatus __cdecl CVWrapGPU::evaluate(class MDataBlock &,class MEvaluationNode co
nst &,class MPlug const &,unsigned int,class MAutoCLMem,class MAutoCLEvent,clas
s MAutoCLMem,class MAutoCLEvent &)" (?evaluate@CVWrapGPU@@UEAA?AW4DeformerStatu
s@MPxGPUDeformer@@AEAVMDataBlock@@AEBVMEvaluationNode@@AEBVMPlug@@IVMAutoCLMem@
@VMAutoCLEvent@@V7@AEAV8@@Z) [C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-m
aster\build\src\cvwrap.vcxproj]
  cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewGe
tKernelWorkGroupInfo referenced in function "public: virtual enum MPxGPUDeforme
r::DeformerStatus __cdecl CVWrapGPU::evaluate(class MDataBlock &,class MEvaluat
ionNode const &,class MPlug const &,unsigned int,class MAutoCLMem,class MAutoCL
Event,class MAutoCLMem,class MAutoCLEvent &)" (?evaluate@CVWrapGPU@@UEAA?AW4Def
ormerStatus@MPxGPUDeformer@@AEAVMDataBlock@@AEBVMEvaluationNode@@AEBVMPlug@@IVM
AutoCLMem@@VMAutoCLEvent@@V7@AEAV8@@Z) [C:\Users\PMnicolai\Desktop\cvwrap-maste
r\cvwrap-master\build\src\cvwrap.vcxproj]
  cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewEn
queueWriteBuffer referenced in function "int __cdecl EnqueueBuffer(class MAutoC
LMem &,unsigned __int64,void *)" (?EnqueueBuffer@@YAHAEAVMAutoCLMem@@_KPEAX@Z)
[C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\src\cvwrap.vcxpro
j]
  cvWrapDeformer.obj : error LNK2019: unresolved external symbol __imp___clewEn
queueNDRangeKernel referenced in function "public: virtual enum MPxGPUDeformer:
:DeformerStatus __cdecl CVWrapGPU::evaluate(class MDataBlock &,class MEvaluatio
nNode const &,class MPlug const &,unsigned int,class MAutoCLMem,class MAutoCLEv
ent,class MAutoCLMem,class MAutoCLEvent &)" (?evaluate@CVWrapGPU@@UEAA?AW4Defor
merStatus@MPxGPUDeformer@@AEAVMDataBlock@@AEBVMEvaluationNode@@AEBVMPlug@@IVMAu
toCLMem@@VMAutoCLEvent@@V7@AEAV8@@Z) [C:\Users\PMnicolai\Desktop\cvwrap-master\
cvwrap-master\build\src\cvwrap.vcxproj]
  C:\Users\PMnicolai\Desktop\cvwrap-master\cvwrap-master\build\src\Release\cvwr
ap.mll : fatal error LNK1120: 5 unresolved externals [C:\Users\PMnicolai\Deskto
p\cvwrap-master\cvwrap-master\build\src\cvwrap.vcxproj]

```
0 Warning(s)
6 Error(s)
```

Time Elapsed 00:00:03.54

---

**Comment by giordi91** [comment]
HI can you post a screenshot of the opened project in VS with the library and library path generated?

**Comment by chadmv** [comment]
Looks like it's having issues linking with the clew library.  Does this file exist?  C:\Program Files\Autodesk\Maya2016\lib\clew.lib.  It should be listed in your project linker input dependencies.

**Comment by ghost** [comment]
hi 
ty for the reply, i got it to work when i download the module repository to and put it under cgcmake.
sorry about that, its all good now, thank you again chad for sharing, looking forward to play around with it.

**Comment by chadmv** [comment]
Yes when you clone the repository, you have to make sure to initialize the submodules:

```
git submodule update --init
```
