### ISSUE TITLE
Glitch in opencl implementation

### ISSUE THREAD

**Issue by giordi91** [chadmv/cvwrap#2]
Hi Chad I was evaluating the plugin and found an issue with the OpenCL implementation.
I just created a simple sphere as a driver (382 vertices) and I used to wrap another sphere of 40k~ vertices.
Works good on CPU , when switching to GPU i start to get this kind of glitches:
![wrap](https://cloud.githubusercontent.com/assets/2525797/11211580/4fb657b0-8d28-11e5-900d-e877fe0b0ee7.jpg)

The glitch is not constant, each frame happens in a different position, and if getting back to the same frame the glitch is somewhere else, from the look of it looks like a memory related issue, I did not have time to look at the code yet, but maybe do you know on top of your head what can be causing this?

M.

**Comment by chadmv** [comment]
Yeah, could be an issue.  Can you send me the Maya scene?

**Comment by giordi91** [comment]
Hi sorry for late reply, I was busy at work and did not find time to build the scene.
Here attached the scene and also a screen grab of the glitch.
Here at dneg we use Centos 6. I will try to recompile at home on my windows box and see if the glitch appears, I am also running on fairly new drivers, I think nvidia 352~

https://drive.google.com/file/d/0B5GRnmB-5ze2WTA2YThwRjhfV2RaSmpFVTJlcEVOYzQ4VUU0/view?usp=sharing

**Comment by chadmv** [comment]
I'm unable to see the artifacts on my machine at home (Windows 10, GTX 980, 358.91).  It might be linux driver-related.  Are you able to update drivers and try again?

**Comment by giordi91** [comment]
Hi, I cannot update the driver on the work machine easily so I will first try at home, I own a centos 7 box on which I can put the latest driver and a windows 10 machine aswell. And see if I can reproduce, I will let you know.
Do you know if there is any way to tell maya to run on an integrated intel graphic ? The reason why I am asking is because if we do so Interl has a lot of nice tool for debugging opencl (I guess is a whole lot easier to debug it when you are on the CPU). I know by the fault maya tries to get the most powerful device?

M.

**Comment by chadmv** [comment]
Hmmm..I've never seen any option that lets you choose which adapter to use in Maya.
