### ISSUE TITLE
Maya wrap faster than cvWrap on linux/maya 2016

### ISSUE THREAD

**Issue by AtonLerin** [chadmv/cvwrap#3]
Hello,

We have done some benchmarks at work with your deformer. cvWrap is faster on older version 2014,2015 for instance but on maya 2016 we actually figured out maya wrap is much faster.

Any thoughts about it ? Explanation etc... Parallele evaluation mode ? Or Autodesk did some improvement to the maya wrap itself ?

Best
A.

**Comment by chadmv** [comment]
Hi Aton,

Autodesk did some improvements to the wrap itself in terms of speed and memory usage.  Sometimes even a 20x speed improvement!  I would say when deciding between the two now, you'll need to compare workflows (bind/rebind) and the actual deformation effect.

**Comment by AtonLerin** [comment]
Very interesting, I'll cc your answers to the team.

Have a wonderful day Chad.
A.

**Comment by zewt** [comment]
It's still massively faster for dense geometry.  Unless exclusive is on, Maya's wrap starts to fall apart with 100k vertex meshes and uses a ton of memory.  cvwrap isn't as tunable, but it still scales a lot better.

**Comment by zewt** [comment]
(Talking about initial setup time--if that succeeds it's usually very fast, but if it takes a full minute to create the deformer on scene load, that's not very useful.)

**Comment by AtonLerin** [comment]
Good to know. I didn't say I throwed the cvWrap, it's good to have different options. But before the maya wrap was NOT an option at all ... more this way :)

About Exclusive bind
When on, the wrap deformer’s target surface will behave like a rigid bind skin and Weight Threshold is disabled. Each surface point on the wrap deformer’s target surface will only be affected by a single wrap influence object point.

So for the >100k mesh you mentioned. I would break it down into patchs:
Use a smooth non exclusive bind (the slow one) or a cvWrap between patch/drivenGeos. 
Then between patchs/finalgeo, as they share the same vtxs topo (but not the same count). Then I can use a wrap in exclusive mode. Or any fancy vtx to vtx deformer (very fast). ---> make me think on 2016 I didn't benchmark the two... TODO...

Does it sounds correct to you ?
A.

**Comment by AtonLerin** [comment]
Coming back with some edits... Deformation speaking it's actually very true that cvWrap gives much cleaner results in some circumstances. For instance I have just tested to wrap meniscus and eyes cornerBit to a face geometry. So they follow the face. Only the cvWrap gives me a good result.

I must admit... Making conclusion from benchmarks without the global context leads to critical mistakes.

**Comment by chadmv** [comment]
Closing.
