### ISSUE TITLE
Compile error in 2016.5 (ext 2)

### ISSUE THREAD

**Issue by italic-r** [chadmv/cvwrap#7]
I've used this plugin in the past with nice results and wanted to build it for 2016.5, but it gives me an error with latest master branch. I'm not a C programmer, so I'm pretty helpless. Here is my build log: 

$ make -j1
[ 20%] Building CXX object src/CMakeFiles/cvwrap.dir/cvWrapDeformer.cpp.o  
/home/italic/src/addons/cvwrap/src/cvWrapDeformer.cpp: In constructor ‘CVWrap::CVWrap()’:
/home/italic/src/addons/cvwrap/src/cvWrapDeformer.cpp:217:22: warning: converting to non-pointer type ‘MCallbackId {aka long unsigned int}’ from NULL [-Wconversion-null]
   onDeleteCallbackId = NULL;  
                      ^
/home/italic/src/addons/cvwrap/src/cvWrapDeformer.cpp: In destructor ‘virtual CVWrap::~CVWrap()’:
/home/italic/src/addons/cvwrap/src/cvWrapDeformer.cpp:221:28: warning: NULL used in arithmetic [-Wpointer-arith]
   if(onDeleteCallbackId != NULL)  
                            ^
/home/italic/src/addons/cvwrap/src/cvWrapDeformer.cpp: In member function ‘virtual void CVWrap::postConstructor()’:
/home/italic/src/addons/cvwrap/src/cvWrapDeformer.cpp:240:112: error: no matching function for call to ‘MNodeMessage::addNodeAboutToDeleteCallback(MObject, void (&)(MObject&, MDGModifier&, void_), NULL, MStatus_)’
   onDeleteCallbackId = MNodeMessage::addNodeAboutToDeleteCallback(thisMObject(), aboutToDeleteCB, NULL, &status);  
                                                                                                                ^
/home/italic/src/addons/cvwrap/src/cvWrapDeformer.cpp:240:112: note: candidates are:
In file included from /home/italic/src/addons/cvwrap/src/cvWrapDeformer.cpp:12:0:
/usr/autodesk/maya2016.5/include/maya/MNodeMessage.h:175:21: note: static MCallbackId MNodeMessage::addNodeAboutToDeleteCallback(MObject&, MMessage::MNodeModifierFunction, void_, MStatus_)
  static MCallbackId addNodeAboutToDeleteCallback(
                     ^
/usr/autodesk/maya2016.5/include/maya/MNodeMessage.h:175:21: note:   no known conversion for argument 1 from ‘MObject’ to ‘MObject&’
/usr/autodesk/maya2016.5/include/maya/MNodeMessage.h:226:21: note: static MCallbackId MNodeMessage::addNodeAboutToDeleteCallback(MObject&, MMessage::MModifierFunction, void_, MStatus_)
  static MCallbackId addNodeAboutToDeleteCallback(
                     ^
/usr/autodesk/maya2016.5/include/maya/MNodeMessage.h:226:21: note:   no known conversion for argument 1 from ‘MObject’ to ‘MObject&’
make[2]: **\* [src/CMakeFiles/cvwrap.dir/cvWrapDeformer.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/cvwrap.dir/all] Error 2
make: **\* [all] Error 2

**Comment by renaudll** [comment]
Had the same issue when building from CentOS6.
gcc 4.4.7 seem to behave differently.

at line 240, replace:
`onDeleteCallbackId = MNodeMessage::addNodeAboutToDeleteCallback(thisMObject(), aboutToDeleteCB, NULL, &status);`

by:
`MObject myMObject = thisMObject();`
`onDeleteCallbackId = MNodeMessage::addNodeAboutToDeleteCallback(myMObject, aboutToDeleteCB, NULL, &status);`
